name: Esteira CI/CD Python baseada em GitHub Actions
on:
  push:
    branches: [main]
jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      CI_API_URL: ${{ secrets.CI_API_URL }}
      CI_API_TOKEN: ${{ secrets.CI_API_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: flake8 - Linting
        run: |
          python -m flake8 app

      - name: Pytest - Run tests
        run: |
            python -m pytest tests   
            
      - name: bandit - Security checks
        run: |
          python -m bandit -r app

      - name: mypy - Type checking
        run: |
            python -m mypy app      
      - name: radon 
        run: |
            python -m radon cc app -a

      - name: Notify external API
        run: |
          curl --fail --show-error --silent \
            -X POST "$www.google.com" \
            -H "Content-Type: application/json" \